{{- if .Values.sealedSecret.enabled -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "tasky.sealedSecretName" . }}
  labels:
    {{- include "tasky.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    {{- range $key, $value := .Values.sealedSecret.encryptedData }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  template:
    metadata:
      name: {{ include "tasky.sealedSecretName" . }}
      namespace: {{ .Release.Namespace }}
{{- end }}
