apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasky
  labels:
    app: tasky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasky
  template:
    metadata:
      labels:
        app: tasky
    spec:
      containers:
      - name: tasky
        image: jicowan/tasky:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: tasky-secrets
              key: mongodb-uri
        imagePullPolicy: Always
      serviceAccountName: tasky-sa
---
apiVersion: v1
kind: Service
metadata:
  name: tasky-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: tasky
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tasky-ingress
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "ip"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/group.name: "tasky"
spec:
  rules:
    - host: tasky.jicomusic.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tasky-service
                port:
                  number: 80
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tasky-secrets
  namespace: default
spec:
  encryptedData:
    MONGODB_URI: AgDO1iLtu3fKuEUdFBV/qaLp1a4pxB3qBzhkdVabnsXawe/iotaGdlJpJH6OidUifhQaE8SWzDsiQcvokeoRwAGCaykBgEuhmwCs4m4OhnND0Q1XoJS29CGZpggKK6X+YNAzZwBNAJq93jlNAy29Oi1vBhPTRMJ0nNVbmpMx32uRl//AW7kNtqejdwCPghIQBRSoGQhXJUl7M4m+crbcV6sGaDnObpIsTPSdr6HsMkN5MBXXtkt5zB9u4BpDt2PzPTczkYsTZCP4gbqo38DeTv2xnt9sbBSzz4q37u0IinlEzYswL3DngOgBZY0uCZiNNZxk4kXCa6Hgrn3tPJIva/K85vFZdtkhb8pyfBu+dWiNIvL2XzPg3uQGrjJEXcQ8X0pgWPPHzSvtTDtThuAnY9c3ixTKmoCb874GdzOfn+xHj2n1a+0Uc7IzVLmvqVMPoRcha8UvKYSunz9zrFBvSZo0+Yq2zRE7fcvuOIq+vAgJz2JYKWFV83VOuSxYwH4ALUxDgsjcPUIkg+iEpdtElC7qrWU9P4lJ8yZ4aoJ5/XNdgcaHeApdceQk2/qsuPHHRlsaPEPMw17UOrhbxaoRo2dLY3sath6UMyMfaghi8HyUQo4WFW1X7THJ8yYTXHMlRdywgPC8A5DejX51PEBefpR5ULKriLaCHf2Y5eXWVDh+LKYqRna+t3jxcs3WWbb7WWYfpIpKoK73wcJq3ww4N+1i/Pj9Ra7kBKac4q+Cp2l+nvvvwti6w7zv
  template:
    metadata:
      creationTimestamp: null
      name: tasky-secrets
      namespace: default
    type: Opaque
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tasky-crb
subjects:
  - kind: ServiceAccount
    name: tasky-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tasky-sa
  namespace: default
