apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasky
  labels:
    app: tasky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasky
  template:
    metadata:
      labels:
        app: tasky
    spec:
      containers:
      - name: tasky
        image: jicowan/tasky:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: tasky-secrets
              key: mongodb-uri
      serviceAccountName: tasky-sa
---
apiVersion: v1
kind: Service
metadata:
  name: tasky-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: tasky
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tasky-ingress
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "ip"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/group.name: "tasky"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tasky-service
                port:
                  number: 80
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tasky-secrets
  namespace: tasky
spec:
  encryptedData:
    mongodb_uri: AgAG1bKUKz1CrDaMwSK6dF1Uzzztj3V1zAa98MUemVMtwdh8FIMCny6nUAVv57PPIZ25fcVIPoUjdyVqY2iiiuqwAFo3kYL4uL/EJqRUQvJcm4Tuf1KT3DbP47z9MAd3RCfVmhYjlv9aeiQNn9Nayb0XzsVyfKBxRNb8oxCnEAcJUEYR+YlTT3OLH8s1Wmu+sH8bd37Rg3lzBKkPxKfySjL8Aj3pCPKGQInlHz6mvm8RoCWqPze+ZpIJrzxEoy9CfV1qmdwIDG0lYh9YDLHZGIYrhfyW9mf3z+xX2Q0qYr4vLGDItKdcH/bYOaLeJMQGtLaEv2L+rvTTFzOkglUYa/8jN7wGxpW6hbxx49vaAnF+0HFdcnqi/4BFOHbc5d66MFIMd28Sn/wARpFeCogGNxblsu+JUL8zbBy6OrsdyeJwj2KyXoNcBRqpGjphElCiSBhm/GWR63iNuR+fMWto6Gr/MI18c8DSo8foVNliQiDJ2N5rKiNGcjr9s+loKY1cllY2WTyABnsbHCCM5DjDL48jz9Z2Do2HTSavTiyhYe3mjvZ+3ZteAw2DZzyO6y6928Fsn08cojITqnIOSPw5MwRYxWATfa/ymKLeaHBt070fy8ml3zUmkGBs6E1rzzzh+Um/kdidGX/zwcpK0C3xL3GqBi26UFXLxGHQFkHslYwKKYPjA0ugMXCbB1eOVAuv+Iv/6acXIsGQWInOzvx68DzmuCMDXvejF17ld+sWwFa8tTGVqv3rnNa31eCZGFb2Ic8wnHuRaKSPSQ==
  template:
    metadata:
      name: tasky-secrets
      namespace: tasky
    type: Opaque
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tasky-crb
subjects:
  - kind: ServiceAccount
    name: tasky-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tasky-sa
  namespace: default